### ISSUE TITLE
T-07 - Cambios Acceso wall y profile

### ISSUE THREAD

**Issue by IvanSevilla** [UB-ES-2018/faceduck#95]
Se puede entrar sin hacer login, esto es debido al tiempo de expiración del authoritation token, tendría que ser una o dos horas de tiempo de expiración

**Comment by ifrins** [comment]
Define se puede entrar sin hacer login. Que el token ahora no expire es como dijimos que lo haríamos. Es eso u otra cosa?

**Comment by IvanSevilla** [comment]
tendríamos que hacer que expire pero con un tiempo superior

**Comment by IvanSevilla** [comment]
hay un código ya hecho que no permite entrar a determinadas vistas si ha expirado el access token

**Comment by IvanSevilla** [comment]
deja lo que hay, puede que el error este en front

**Comment by 3nr1c** [comment]
En front solo está implementada la redirección a Home sin access-token en la ruta /wall, habría que activarlo en el resto. Aunque también hay que decir que sería mejor tener una especie de trait importable desde las páginas donde queramos este comportamiento, así que mejor no hacer copy pegy (asumo que en la docu de Vuejs estará explicado).

**Comment by dabytmc** [comment]
Fixed by #106
