### ISSUE TITLE
T-10 - Arreglar en Frontend birthdate return format (2h)

### ISSUE THREAD

**Issue by IvanSevilla** [UB-ES-2018/faceduck#98]
date format dd/mm/yyyy

**Comment by dabytmc** [comment]
Yo creo que se deberia hacer en frontend con una libreria de javascript (del tipo *moment.js*). Si que es cierto que en la definición de la API faltaria especificar cual és el formato de date retornada, pero este no deberia adaptarse a las necessidades de formato de cara al usuario.
